module Hog
  class PigSchema
    def schema(tuple)
      "\n--\n-- This schema was auto generated by Hog v#{Hog::VERSION}.\n--\n#{tuple.fields.map{|f| "\t#{field(f)} -- #{f.opts.to_s}" }.join(",\n")}"
    end

    def field(f)
      "#{f.name}:#{f.type}"
    end

  end
end
