module Hog
  class PigSchema
    def schema(tuple)
      "\n--\n-- This schema was auto generated by Hog v#{Hog::VERSION}.#{tuple.fields.map{|f| "\n\t-- #{f.opts.to_s}\n\t#{field(f)}" }.join(",\n")}"
    end

    def field(f)
      "#{f.name}:#{f.type}"
    end

  end
end
